USE ProductsDatabase
DECLARE @ROW_COUNTER BIGINT
SET @ROW_COUNTER=0
BEGIN TRY
	BEGIN TRANSACTION
		--FOR TABLE CLEANUP
		--TRUNCATE TABLE Products 
		--ALTER TABLE Products DROP CONSTRAINT [FK_Products_ToTable] 		
		--TRUNCATE TABLE Category
		--ALTER TABLE Products ADD CONSTRAINT [FK_Products_ToTable] FOREIGN KEY ([Category_CategoryId]) REFERENCES [Category]([Id])
		--FOR TABLE CLEANUP

		IF NOT EXISTS (SELECT Description FROM Products WHERE Description = 'HP MOUSE') INSERT INTO Products (Description,Price) VALUES ('HP MOUSE',10)
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT
	
		IF NOT EXISTS (SELECT Description FROM Products WHERE Description = 'HP MOUSE BLUETOOTH') INSERT INTO Products (Description,Price) VALUES ('HP MOUSE BLUETOOTH',10)
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT
	
		IF NOT EXISTS (SELECT Description FROM Products WHERE Description = 'HP MOUSE USB') INSERT INTO Products (Description,Price) VALUES ('HP MOUSE USB',10)
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT
	
		IF NOT EXISTS (SELECT Description FROM Products WHERE Description = 'HP MONITOR') INSERT INTO Products (Description,Price) VALUES ('HP MONITOR',100)
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT
	
		IF NOT EXISTS (SELECT Description FROM Products WHERE Description = 'HP MONITOR 24') INSERT INTO Products (Description,Price) VALUES ('HP MONITOR 24',100)
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT
	
		IF NOT EXISTS (SELECT Description FROM Products WHERE Description = 'HP MONITOR 21') INSERT INTO Products (Description,Price) VALUES ('HP MONITOR 21',99)	
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT		
		
		IF NOT EXISTS (SELECT Description FROM Category WHERE Description = 'KEYBOARD') INSERT INTO Category (Description) VALUES ('KEYBOARD')	
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT

		IF NOT EXISTS (SELECT Description FROM Products WHERE Description = 'HP KEYBOARD') INSERT INTO Products (Description,Price,Category_CategoryId) VALUES ('HP KEYBOARD',15.99,(SELECT Id FROM Category WHERE Id=1 AND Description='KEYBOARD'))	
		SET @ROW_COUNTER = @ROW_COUNTER + @@ROWCOUNT

		--FOR TEST TRY CATCH
		--SELECT 55/0
		
	IF @ROW_COUNTER <> 8	
	BEGIN
		PRINT CONCAT('ROLLBACK ROWCOUNT: ', CONVERT(VARCHAR(50), @ROW_COUNTER))			
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT CONCAT('COMMIT ROWCOUNT: ', CONVERT(VARCHAR(50), @ROW_COUNTER))		
		COMMIT TRANSACTION
	END
END TRY
BEGIN CATCH
	PRINT CONCAT('CATCH: ',ERROR_MESSAGE(),' ',ERROR_SEVERITY())
	ROLLBACK TRANSACTION
END CATCH